name: '${name}'
version: '${version}'
main: kr.rtustudio.framework.bukkit.plugin.RSFramework
description: Framework of RSPlugins, developed by IPECTER 이팩터
api-version: 1.20
folia-supported: true
authors: [ '${author}' ]
softdepend: [ PlaceholderAPI, packetevents, Nexo, ItemsAdder, Oraxen, EcoItems, MMOItems ]
